#! /usr/bin/env bash


cd "$HOME"/Music/ || exit

while true;
do
    seconds="$((10#$1*60))"
    mplayer -endpos 0:0:3 gong.opus &> /dev/null
    while [ $seconds -gt 0 ]; do
        echo -ne "$(("$seconds" / 60)):$(("$seconds" % 60))\033[0K\r"
       sleep 1
       : $((seconds--))
    done
done
