#! /usr/bin/env bash

cd "$HOME"/Videos || exit
mkdir Priority
cd Priority || exit
touch archive.txt
yt-dlp --download-archive archive.txt https://www.youtube.com/playlist?list=PL9d3JV6oTebyRxpegEvVnBg81CMNb-x0K

cd "$HOME"/Videos || exit
mkdir Heroes
cd Heroes || exit
touch archive.txt
yt-dlp --download-archive archive.txt https://www.youtube.com/playlist?list=PL9d3JV6oTebxJq0SBKkr5GIbqfFFv5SPq
cd "$HOME"/Videos || exit
mkdir -p Gophercon/Top
cd Gophercon/Top || exit
touch archive.txt
yt-dlp --download-archive archive.txt https://www.youtube.com/playlist?list=PL9d3JV6oTebwuOQOdQQ6BrbXxttGWpgjm

cd "$HOME"/Videos || exit
mkdir -p Gophercon/2024/Lightning
cd Gophercon/2024/Lightning || exit
touch archive.txt
yt-dlp --download-archive archive.txt https://www.youtube.com/playlist?list=PL2ntRZ1ySWBdEP9_4K_HTlvOk6orXxxXy

cd "$HOME"/Videos || exit
mkdir -p Gophercon/2024/Talks
cd Gophercon/2024/Talks || exit
touch archive.txt
yt-dlp --download-archive archive.txt https://www.youtube.com/playlist?list=PL2ntRZ1ySWBdtH-tLdfcDJaWABxySlkRj

cd "$HOME"/Music || exit
mkdir study
cd study || exit
touch archive.txt
yt-dlp --download-archive archive.txt -x  --audio-quality 0 https://www.youtube.com/playlist?list=PL9d3JV6oTebwRR2kVcGQ6_Qgc0LPFhTT6

cd "$HOME"/Videos || exit
mkdir watchlater
cd watchlater || exit
touch archive.txt
yt-dlp --download-archive archive.txt https://www.youtube.com/playlist?list=WL --cookies-from-browser firefox
